### ISSUE TITLE
Simplify .github/workflows/check-models.yml

### ISSUE THREAD

**Issue by corinfinite** [corinfinite/openai-model-tracker#9]
@MentatBot We should simplify .github/workflows/check-models.yml, based on the following article and by combining the later steps which are committing files, I don't think we need to have a separate step for running the update subcommand and committing the changes 

From https://joaodlf.com/using-poetry-in-github-actions-the-easy-way
```
steps:
  - uses: actions/checkout@v1

  - name: Setup Python
    uses: actions/setup-python@v2
    with:
      python-version: 3.10.0

  - name: Install poetry
    run: |
      python -m pip install poetry==1.1.11

  - name: Configure poetry
    run: |
      python -m poetry config virtualenvs.in-project true

  - name: Cache the virtualenv
    uses: actions/cache@v2
    with:
      path: ./.venv
      key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}

  - name: Install dependencies
    run: |
      python -m poetry install

  - name: Run tests
    run: |
      python -m poetry run python -m pytest -sxv

```
